export const translations = {
  en: { dropVideo: "Click or drag video here", fileSelected: "File Selected", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "OUTPUT FORMAT", quality: "QUALITY", sampleRate: "Sample Rate", channels: "Channels", bitrate: "Bitrate", convertBtn: "Convert to Audio", convertingBtn: "Converting...", doneBtn: "Done!", finalizing: "Finalizing...", history: "CONVERSION HISTORY", settings: "Settings", language: "Language", help: "Help & Tutorial", about: "About EncoXaudio", version: "Version 1.0.0", back: "Back", noHistory: "No conversions yet." },
  hi: { dropVideo: "वीडियो यहाँ खींचें या क्लिक करें", fileSelected: "फ़ाइल चुनी गई", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "आउटपुट फॉर्मेट", quality: "गुणवत्ता", sampleRate: "सैंपल रेट", channels: "चैनल्स", bitrate: "बिटरेट", convertBtn: "ऑडियो में बदलें", convertingBtn: "बदल रहा है...", doneBtn: "हो गया!", finalizing: "अंतिम रूप दिया जा रहा है...", history: "रूपांतरण इतिहास", settings: "सेटिंग्स", language: "भाषा", help: "मदद और ट्यूटोरियल", about: "EncoXaudio के बारे में", version: "संस्करण 1.0.0", back: "पीछे", noHistory: "अभी तक कोई रूपांतरण नहीं।" },
  es: { dropVideo: "Haz clic o arrastra el video aquí", fileSelected: "Archivo seleccionado", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "FORMATO DE SALIDA", quality: "CALIDAD", sampleRate: "Frecuencia", channels: "Canales", bitrate: "Tasa de bits", convertBtn: "Convertir a Audio", convertingBtn: "Convirtiendo...", doneBtn: "¡Hecho!", finalizing: "Finalizando...", history: "HISTORIAL DE CONVERSIÓN", settings: "Ajustes", language: "Idioma", help: "Ayuda y Tutorial", about: "Acerca de EncoXaudio", version: "Versión 1.0.0", back: "Volver", noHistory: "Sin conversiones aún." },
  fr: { dropVideo: "Cliquez ou glissez la vidéo ici", fileSelected: "Fichier sélectionné", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "FORMAT DE SORTIE", quality: "QUALITÉ", sampleRate: "Échantillonnage", channels: "Canaux", bitrate: "Débit", convertBtn: "Convertir en audio", convertingBtn: "Conversion...", doneBtn: "Terminé!", finalizing: "Finalisation...", history: "HISTORIQUE DE CONVERSION", settings: "Paramètres", language: "Langue", help: "Aide et tutoriel", about: "À propos d'EncoXaudio", version: "Version 1.0.0", back: "Retour", noHistory: "Aucune conversion pour le moment." },
  zh: { dropVideo: "点击或拖拽视频到此处", fileSelected: "已选择文件", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "输出格式", quality: "质量", sampleRate: "采样率", channels: "频道", bitrate: "比特率", convertBtn: "转换为音频", convertingBtn: "转换中...", doneBtn: "完成!", finalizing: "定稿...", history: "转换历史", settings: "设置", language: "语言", help: "帮助与教程", about: "关于 EncoXaudio", version: "版本 1.0.0", back: "返回", noHistory: "暂无转换记录。" },
  ar: { dropVideo: "انقر أو اسحب الفيديو هنا", fileSelected: "تم تحديد الملف", formatText: "MP4 • MKV • AVI • MOV • WebM", outputFormat: "صيغة المخرجات", quality: "الجودة", sampleRate: "معدل العينة", channels: "القنوات", bitrate: "معدل البت", convertBtn: "تحويل إلى صوت", convertingBtn: "جاري التحويل...", doneBtn: "تم!", finalizing: "وضع اللمسات الأخيرة...", history: "سجل التحويل", settings: "إعدادات", language: "اللغة", help: "المساعدة والبرنامج التعليمي", about: "حول EncoXaudio", version: "الإصدار 1.0.0", back: "رجوع", noHistory: "لا توجد تحويلات بعد." }
};

export type LanguageKey = keyof typeof translations;